"""empty message

Revision ID: 25d2679494fb
Revises:
Create Date: 2025-01-20 14:42:11.272376

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25d2679494fb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="productstatus"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_name_fulltext", "product", [sa.text("to_tsvector('english', name)")], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_status_id", "product", ["status", "id"], unique=False)
    op.create_index("idx_status_price", "product", ["status", "price"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_status_price", table_name="product")
    op.drop_index("idx_status_id", table_name="product")
    op.drop_index("idx_name_fulltext", table_name="product", postgresql_using="gin")
    op.drop_table("product")
    # ### end Alembic commands ###
