services:
  db:
    image: postgres:16.1
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  graphql-sample:
    image: graphql-sample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URI: "postgresql+asyncpg://postgres:password@db:5432/appdev"
    depends_on:
      - db
    command: sh -c 'sleep 3; alembic upgrade head && fastapi run'
    env_file:
      - .env
    ports:
      - 8000:8000

volumes:
  app-db-data:
