"""empty message

Revision ID: 7a0b90c8c9a6
Revises:
Create Date: 2025-01-18 11:05:09.342872

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a0b90c8c9a6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="productstatus"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_name_fulltext", "product", [sa.text("to_tsvector('english', name)")], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_status_id", "product", ["status", "id"], unique=False)
    op.create_index("idx_status_price", "product", ["status", "price"], unique=False)
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_priority", "image", ["priority"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_priority", table_name="image")
    op.drop_table("image")
    op.drop_index("idx_status_price", table_name="product")
    op.drop_index("idx_status_id", table_name="product")
    op.drop_index("idx_name_fulltext", table_name="product", postgresql_using="gin")
    op.drop_table("product")
    # ### end Alembic commands ###
