"""empty message

Revision ID: 281e261bfc69
Revises: 94a45c6c7927
Create Date: 2025-01-19 15:41:17.503917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "281e261bfc69"
down_revision: str | None = "94a45c6c7927"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("id", sa.Integer(), nullable=False))
    op.create_unique_constraint("unique_product_id_url", "image", ["product_id", "url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_product_id_url", "image", type_="unique")
    op.drop_column("image", "id")
    # ### end Alembic commands ###
